# Generated by Django 2.0 on 2017-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='description',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
