# Generated by Django 2.0 on 2018-01-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0003_typeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='typeProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeProduct', to='picker.TypeProduct'),
        ),
    ]
